// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {goldsrc} from '../models';

export function OpenDemo():Promise<goldsrc.Demo>;

export function ParseDemo(arg1:string):Promise<goldsrc.Demo>;
