// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDemo() {
  return window['go']['main']['App']['OpenDemo']();
}

export function ParseDemo(arg1) {
  return window['go']['main']['App']['ParseDemo'](arg1);
}

export function SavePlayerReplacement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePlayerReplacement'](arg1, arg2, arg3, arg4);
}

export function SavePrefixedPlayers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePrefixedPlayers'](arg1, arg2, arg3);
}
