// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDemo() {
  return window['go']['main']['App']['OpenDemo']();
}

export function ParseDemo(arg1) {
  return window['go']['main']['App']['ParseDemo'](arg1);
}
